# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{formtastic}
  s.version = "1.0.0.beta"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin French"]
  s.date = %q{2010-06-07}
  s.description = %q{A Rails form builder plugin/gem with semantically rich and accessible markup}
  s.email = %q{justin@indent.com.au}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "generators/form/USAGE",
     "generators/form/form_generator.rb",
     "generators/form/templates/view__form.html.erb",
     "generators/form/templates/view__form.html.haml",
     "generators/formtastic/formtastic_generator.rb",
     "generators/formtastic/templates/formtastic.css",
     "generators/formtastic/templates/formtastic.rb",
     "generators/formtastic/templates/formtastic_changes.css",
     "generators/formtastic_stylesheets/formtastic_stylesheets_generator.rb",
     "lib/formtastic.rb",
     "lib/formtastic/i18n.rb",
     "lib/formtastic/layout_helper.rb",
     "lib/formtastic/util.rb",
     "lib/locale/en.yml",
     "rails/init.rb",
     "spec/buttons_spec.rb",
     "spec/commit_button_spec.rb",
     "spec/custom_builder_spec.rb",
     "spec/custom_macros.rb",
     "spec/defaults_spec.rb",
     "spec/error_proc_spec.rb",
     "spec/errors_spec.rb",
     "spec/form_helper_spec.rb",
     "spec/i18n_spec.rb",
     "spec/include_blank_spec.rb",
     "spec/input_spec.rb",
     "spec/inputs/boolean_input_spec.rb",
     "spec/inputs/check_boxes_input_spec.rb",
     "spec/inputs/country_input_spec.rb",
     "spec/inputs/date_input_spec.rb",
     "spec/inputs/datetime_input_spec.rb",
     "spec/inputs/file_input_spec.rb",
     "spec/inputs/hidden_input_spec.rb",
     "spec/inputs/numeric_input_spec.rb",
     "spec/inputs/password_input_spec.rb",
     "spec/inputs/radio_input_spec.rb",
     "spec/inputs/select_input_spec.rb",
     "spec/inputs/string_input_spec.rb",
     "spec/inputs/text_input_spec.rb",
     "spec/inputs/time_input_spec.rb",
     "spec/inputs/time_zone_input_spec.rb",
     "spec/inputs_spec.rb",
     "spec/label_spec.rb",
     "spec/layout_helper_spec.rb",
     "spec/semantic_errors_spec.rb",
     "spec/semantic_fields_for_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/justinfrench/formtastic/tree/master}
  s.post_install_message = %q{
  ========================================================================
  Thanks for installing Formtastic!
  ------------------------------------------------------------------------
  You can now (optionally) run the generator to copy some stylesheets and
  a config initializer into your application:
    ./script/generate formtastic

  To generate some semantic form markup for your existing models, just run:
    ./script/generate form MODEL_NAME

  Find out more and get involved:
    http://github.com/justinfrench/formtastic
    http://groups.google.com.au/group/formtastic
  ========================================================================
  }
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Rails form builder plugin/gem with semantically rich and accessible markup}
  s.test_files = [
    "spec/buttons_spec.rb",
     "spec/commit_button_spec.rb",
     "spec/custom_builder_spec.rb",
     "spec/custom_macros.rb",
     "spec/defaults_spec.rb",
     "spec/error_proc_spec.rb",
     "spec/errors_spec.rb",
     "spec/form_helper_spec.rb",
     "spec/i18n_spec.rb",
     "spec/include_blank_spec.rb",
     "spec/input_spec.rb",
     "spec/inputs/boolean_input_spec.rb",
     "spec/inputs/check_boxes_input_spec.rb",
     "spec/inputs/country_input_spec.rb",
     "spec/inputs/date_input_spec.rb",
     "spec/inputs/datetime_input_spec.rb",
     "spec/inputs/file_input_spec.rb",
     "spec/inputs/hidden_input_spec.rb",
     "spec/inputs/numeric_input_spec.rb",
     "spec/inputs/password_input_spec.rb",
     "spec/inputs/radio_input_spec.rb",
     "spec/inputs/select_input_spec.rb",
     "spec/inputs/string_input_spec.rb",
     "spec/inputs/text_input_spec.rb",
     "spec/inputs/time_input_spec.rb",
     "spec/inputs/time_zone_input_spec.rb",
     "spec/inputs_spec.rb",
     "spec/label_spec.rb",
     "spec/layout_helper_spec.rb",
     "spec/semantic_errors_spec.rb",
     "spec/semantic_fields_for_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.0"])
      s.add_runtime_dependency(%q<actionpack>, [">= 2.3.0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 1.2.6"])
      s.add_development_dependency(%q<rspec_tag_matchers>, [">= 1.0.0"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.0"])
      s.add_dependency(%q<actionpack>, [">= 2.3.0"])
      s.add_dependency(%q<rspec-rails>, [">= 1.2.6"])
      s.add_dependency(%q<rspec_tag_matchers>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.0"])
    s.add_dependency(%q<actionpack>, [">= 2.3.0"])
    s.add_dependency(%q<rspec-rails>, [">= 1.2.6"])
    s.add_dependency(%q<rspec_tag_matchers>, [">= 1.0.0"])
  end
end

