source "https://rubygems.org"

gem "rails", git: "https://github.com/rails/rails.git", branch: "main"
gem "rack", git: "https://github.com/rack/rack.git"
gem "i18n", git: "https://github.com/svenfuchs/i18n.git"
gem "arel", git: "https://github.com/rails/arel.git"
gem "rspec-rails", git: "https://github.com/rspec/rspec-rails.git"
gem "rspec-mocks", git: "https://github.com/rspec/rspec-mocks.git"
gem "rspec-support", git: "https://github.com/rspec/rspec-support.git"
gem "rspec-core", git: "https://github.com/rspec/rspec-core.git"
gem "rspec-expectations", git: "https://github.com/rspec/rspec-expectations.git"

gemspec path: "../.."
