name: test

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        gemfile:
          - gemfiles/rails_6.1/Gemfile
          - gemfiles/rails_7.0/Gemfile
          - gemfiles/rails_7.1/Gemfile
          - gemfiles/rails_edge/Gemfile

        ruby:
          - 2.7
          - 3.0
          - 3.1
          - 3.2
          - 3.3

        include:
          - ruby: 2.6
            gemfile: gemfiles/rails_6.0/Gemfile
          - ruby: 2.7
            gemfile: gemfiles/rails_6.0/Gemfile

        exclude:
          - ruby: 2.7
            gemfile: gemfiles/rails_edge/Gemfile
          - ruby: 3.0
            gemfile: gemfiles/rails_edge/Gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: latest

      - name: Run tests
        run: |
          bundle exec rake spec
          script/integration.sh
        continue-on-error: ${{ matrix.gemfile == 'gemfiles/rails_edge/Gemfile' }}
